### ISSUE TITLE
Docker-Compose for Redis and MongoDB

### ISSUE THREAD

**Issue by wlami** [sharelatex/sharelatex-docker-image#22]
It would be great if one could spin up the redis and mongoDB dependencies as docker container using docker-compose automatically.

**Comment by cahna** [comment]
Like this? (To get this working, I had to apply the fix described in [this issue](https://github.com/sharelatex/sharelatex-docker-image/issues/7))

``` yaml
---
sharelatex_mongodb_data:
  image: mongo:2.6.9
  entrypoint: /bin/true
  volumes:
    - /docker/sharelatex/mongo_data:/data/db

sharelatex_mongodb:
  image: mongo:2.6.9
  volumes_from:
    - sharelatex_mongodb_data

sharelatex_redis_data:
  image: redis
  entrypoint: /bin/true
  volumes:
    - /docker/sharelatex/redis_data:/data

sharelatex_redis:
  image: redis
  command: redis-server --appendonly yes
  volumes_from:
    - sharelatex_redis_data

sharelatex_data:
  image: sharelatex/sharelatex:0.1.4
  entrypoint: /bin/true
  volumes:
    - /docker/sharelatex/data:/var/lib/sharelatex

sharelatex:
  image: sharelatex/sharelatex:0.1.4
  volumes_from:
    - sharelatex_data
  links:
    - sharelatex_mongodb:sharelatex_mongodb
    - sharelatex_redis:sharelatex_redis
  environment:
    # Where your instance is publically available.
    SHARELATEX_SITE_URL: http://example.com

    # The email address where users can reach the person who runs the site.
    SHARELATEX_ADMIN_EMAIL: foo@example.com

    # The name to display when talking about the running app. Defaults to 'ShareLaTex (Community Edition)'.
    SHARELATEX_APP_NAME: Test

    # The URL of the Mongo database to use
    SHARELATEX_MONGO_URL: mongodb://sharelatex_mongodb/sharelatex

    # The host name of the Redis instance to use
    SHARELATEX_REDIS_HOST: sharelatex_redis

    # The port of the Redis instance to use
    SHARELATEX_REDIS_PORT: 6379

    # The password to use when connecting to Redis (if applicable)
    #SHARELATEX_REDIS_PASS:

    # Set to non-zero to use secure cookie. Only use this if your ShareLaTeX instance is running behind a reverse proxy with SSL configured.
    #SHARELATEX_SECURE_COOKIE:
  ports:
    - 80:80
```
