### ISSUE TITLE
migrating from 0.14 github to 0.2 docker

### ISSUE THREAD

**Issue by ghost** [sharelatex/sharelatex-docker-image#39]
Hi,
I'm using a sharelatex server setup on debian jessie.
I used 0.14 from github.
Now I wanted to update to docker to get the newer version as well as making maintenance of the setup easier.

I used this script:
`
docker run -d \
-v /:/var/lib/sharelatex \
--env SHARELATEX_MONGO_URL=mongodb://dockerhost/sharelatex \
--env SHARELATEX_REDIS_HOST=redis://dockerhost/sharelatex \
--env SHARELATEX_SITE_URL=http://localhost:5000 \
-p 5000:80 \
--name=sharelatex \
sharelatex/sharelatex
`

In short, I had stored data from sharelatex in /var/lib/sharelatex (so why change it?), as some backup stuff were already running on this folder.
I wanted to use the same mongodb and redis setup, as before, so I set mongo_url and redis_host to dockerhost. (not sure if this is correct).
then i set the url to localhost:5000 and port 5000:80. But here things get a bit fuzy for me, which ports are what?

As the server has only limited open ports, i have to move it behind a proxy. I use nginx with the config (for the 0.14 github setup).

`        client_max_body_size 50M;
        set $static_path /opt/sharelatex/web/public;

```
    location / {
            proxy_pass http://localhost:3000;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_x_forwarded_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 3m;
            proxy_send_timeout 3m;
    }

    location /socket.io {
            proxy_pass http://localhost:3026;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_x_forwarded_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 3m;
            proxy_send_timeout 3m;
    }

    location /stylesheets {
            expires 1y;
            root $static_path/;
    }

    location /minjs {
            expires 1y;
            root $static_path/;
    }

    location /img {
            expires 1y;
            root $static_path/;
    }
```

`

And things don't work... The thing is also quiet a black box for me... I don't see output, if the script could run or not. 

as texlive 2015 is installed on the dockerhost, I would like to use that installation rather then a new setup inside the docker( how it normally works, as far as i understood). any help?

@henryoswald

**Comment by ghost** [comment]
any help?

**Comment by ghost** [comment]
This docker totally drives me crazy. I thought it would be straight forward, but it totally isn't.

So i have debian server (jessie) with nginx running. On the server i can only use port 80 and 443.
So I need nginx for proxying (because other software is running on this server as well).

I have redis and mongodb running (with sharelatex data from earlier (0.10) github install, which of course I would like to use.

The basic code I ran is 
`#!/usr/bin/env bash

docker run -d \
        -v ~/sharelatex_data:/var/lib/sharelatex \
        -p 80 \
        --name=sharelatex \
        sharelatex/sharelatex
`

I tried switching nginx of using 'service nginx stop', and rerun the code... nothing seems to work. i'm getting 502....

The code above is supposed to download the necessary code right? 
Really quickly I get the terminal back indicating like nothing is happening.

If I ran the code I only get a code of letters and numbers...

does the above code need to be run as root or as user sharelatex?

How can I debug this, as right now it is just a black box to me.

Hopefully somebody can help me out, but not much reaction on this forum... almost seems as the docker file is dead...

**Comment by jazzdd86** [comment]
Hi, the easiest way is to use docker-compose and a seperate compose file for creating the containers.

This is my compose file using an nginx proxy (https://hub.docker.com/r/jwilder/nginx-proxy/):

```
sharelatex:
    container_name: latex
    restart: always
    links:
        - latex_redis:redis
        - latex_mongo:mongo
    volumes:
        - /data/data-latex/texlive:/usr/local/texlive
        - /data/data-latex/files/:/var/lib/sharelatex
    environment:
        - SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex
        - SHARELATEX_REDIS_HOST=redis
        - SHARELATEX_SITE_URL=http://sub.domain.com
        - VIRTUAL_HOST=sub.domain.com
    image: jazzdd/sharelatex

latex_redis:
    container_name: latex_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
        - /data/data-latex/redis:/data
    image: redis

latex_mongo:
    container_name: latex_mongo
    restart: always
    volumes:
        - /data/data-latex/mongo:/data/db
    image: mongo
```

What you could do: Export your redis and mongo db databases. Use the docker compose file above. It links the redis and mongodb containers to the sharelatex container. So you don't have to go through dockerhost. And then import your exported db data to the new database containers.

Alternative: If you still want to use your old setup. Use hostnames/ip addresses instead of dockerhost for the redis and mongodb locations. Don't use localhost for sharelatex_url but the real server host address, eg: http://servername:port, then you have to use the dockercommand with -p port:80 to route the internal http port to the servers external port.

But as you wrote, you want to use a nginx proxy. I would strongly recommend the nginx proxy from jwilder (link see above) as it automatically adds the correct proxy configuration as you start a new container - you only have to use those VIRTUAL_HOST variables - no port forwarding to the host system, no manual proxy configuration - works as a charme.

Hope this helps.
