### ISSUE TITLE
SHARELATEX_MONGO_URL does not take effect

### ISSUE THREAD

**Issue by mcapuccini** [sharelatex/sharelatex-docker-image#48]
Hello. I am trying to run the sharelatex using the following docker-compose yml file.

``` yaml
sharelatex:
    container_name: latex
    restart: always
    links:
        - latex_redis:redis
        - latex_mongo:mongo
    environment:
        - SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex
        - SHARELATEX_REDIS_HOST=redis
        - SHARELATEX_SITE_URL=http://pele.farmbio.uu.se/sharelatex
    ports:
        - 5000:80
    image: sharelatex/sharelatex

latex_redis:
    container_name: latex_redis
    restart: always
    command: redis-server --appendonly yes
    image: redis

latex_mongo:
    container_name: latex_mongo
    restart: always
    image: mongo
```

The problem is that setting SHARELATEX_SITE_URL does not take effect, so the base url of the autogenerated links it is always the hostname of the machine where I am running docker. Is this a bug, or am I missing something?

**Comment by jazzdd86** [comment]
mh, looks ok to me, except if you want to use a different port, you also have to propagate the information to the URL Variable:
`SHARELATEX_SITE_URL=http://pele.farmbio.uu.se:5000/sharelatex`
And I think sharelatex has some issues with subpath as sharelatex root. Maybe you could use another subdomain instead of a subpath (see issue https://github.com/sharelatex/sharelatex-docker-image/issues/44).

The following is my compose file. The difference is, I am using my sharelatex docker image with some fixed issues and a nginx proxy.

The official image still does have some issues, which will need to be fixed with a pull request I submitted a while ago.

```
sharelatex:
    container_name: latex
    restart: always
    links:
        - latex_redis:redis
        - latex_mongo:mongo
    volumes:
        - /data/data-latex/texlive:/usr/local/texlive
        - /data/data-latex/files/:/var/lib/sharelatex
    environment:
        - SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex
        - SHARELATEX_REDIS_HOST=redis
        - SHARELATEX_SITE_URL=http://latex.domain.de
        - VIRTUAL_HOST=latex.domain.de,www.latex.domain.de
    image: jazzdd/sharelatex

latex_redis:
    container_name: latex_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
        - /data/data-latex/redis:/data
    image: redis

latex_mongo:
    container_name: latex_mongo
    restart: always
    volumes:
        - /data/data-latex/mongo:/data/db
    image: mongo
```
