### ISSUE TITLE
Enviroment variable SHARELATEX_EMAIL_SMTP_IGNORE_TLS has no effect

### ISSUE THREAD

**Issue by JanoschDeurer** [sharelatex/sharelatex-docker-image#62]
I'm trying to get e-mail working. When I try to add a new user in the Admin Panel im getting the following error:

>  web.log:{"name":"web-sharelatex","hostname":"30ced72e6a1c","pid":106,"level":50,"err":{"message":"DEPTH_ZERO_SELF_SIGNED_CERT","name":"Error","stack":"Error: DEPTH_ZERO_SELF_SIGNED_CERT\n  at SecurePair.<anonymous> (tls.js:1429:32)\n  at SecurePair.emit (events.js:92:17)\n  at SecurePair.maybeInitFinished (tls.js:1028:10)\n  at CleartextStream.read [as _read] (tls.js:520:13)\n  at CleartextStream.Readable.read (_stream_readable.js:341:10)\n  at EncryptedStream.write [as _write] (tls.js:417:25)\n  at doWrite (_stream_writable.js:226:10)\n  at writeOrBuffer (_stream_writable.js:216:5)\n  at EncryptedStream.Writable.write (_stream_writable.js:183:11)\n  at Socket.ondata (stream.js:51:26)\n  at Socket.emit (events.js:95:17)\n  at Socket.<anonymous> (_stream_readable.js:765:14)\n  at Socket.emit (events.js:92:17)\n  at emitReadable_ (_stream_readable.js:427:10)\n  at emitReadable (_stream_readable.js:423:5)\n  at readableAddChunk (_stream_readable.js:166:9)\n  at Socket.Readable.push (_stream_readable.js:128:10)\n  at TCP.onread (net.js:529:21)\n"},"msg":"error sending message","time":"2016-11-06T12:49:07.020Z","v":0}

Obviously sharelatex is not happy with my self signed certificate. The mailserver is however on the same physical machine as sharelatex which is why I do not use any authentication or encryption. I tried to deactivate TLS by using the env variable SHARELATEX_EMAIL_SMTP_IGNORE_TLS, however the error stays the same. This is my docker-compose.yml file:

```
sharelatex:
  build: ./build/sharelatex
  links:
   - mongo
   - redis
  environment:
    SHARELATEX_SITE_URL: https://tex.example.com
    SHARELATEX_ADMIN_EMAIL: blubb@example.com
    SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
    SHARELATEX_REDIS_HOST: redis

    SHARELATEX_EMAIL_FROM_ADDRESS: blubb@example.com
    SHARELATEX_EMAIL_SMTP_HOST: example.com
    SHARELATEX_EMAIL_SMTP_PORT: 25
    SHARELATEX_EMAIL_SMTP_SECURE: "false"
    SHARELATEX_EMAIL_SMTP_IGNORE_TLS: "true"
  volumes:
   - ./volumes/sharelatex:/var/lib/sharelatex
mongo:
  image: mongo
  volumes:
   - ./volumes/mongo:/data/db
redis:
  image: redis
  command: "redis-server --appendonly yes"
  volumes:
   - ./volumes/redis:/data
```
I do not use example.com but my own domain ;-) I tried using a configuration as in the [example docker-compose file](https://github.com/sharelatex/sharelatex/blob/master/docker-compose.yml) but docker-compose fails with the following error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.sharelatex.environment.SHARELATEX_EMAIL_SMTP_IGNORE_TLS contains true, which is an invalid type, it should be a string, number, or a null
```
I tried using the nodemailer manually in your docker-image and it worked, so my mail server is configured correctly. At this point I'm not sure where to go on with debugging and would appreciate any help.
